### ISSUE TITLE
My config.json doesn't have RawDriver

### ISSUE THREAD

**Issue by ffissore** [bhurlow/machine-share#1]
And import fails with

```
fixing driver..
buffer.js:141
    throw new TypeError('must start with number, buffer, array or string');
    ^

TypeError: must start with number, buffer, array or string
    at fromObject (buffer.js:141:11)
    at new Buffer (buffer.js:62:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/machine-share/driverfix.js:16:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

**Comment by bhurlow** [comment]
@ffissore which version of docker-machine are you running? They took out the raw-driver thing a few versions ago...

**Comment by ffissore** [comment]
Latest. Indeed, I then found the issue

**Comment by ffissore** [comment]
I've put your scripts here https://github.com/ffissore/docker-scripts although they fail when the two client don't share the same CA. I'll work on that
