### ISSUE TITLE
Missing `.docker/machine/certs/` folder

### ISSUE THREAD

**Issue by ivanistheone** [bhurlow/machine-share#28]
When trying to `machine-export` using latest machine-share and docker-machine version 0.14.0,
I get some certs-missing errors.

The docker machine confg for the machine in question states:

```
        "AuthOptions": {
            "CertDir": "/Users/ivan/.docker/machine/certs",
            "CaCertPath": "/Users/ivan/.docker/machine/certs/ca.pem",
            "CaPrivateKeyPath": "/Users/ivan/.docker/machine/certs/ca-key.pem",
```

But the folder `.docker/machine/certs/` doesn't exist so

```
Error: ENOENT: no such file or directory, open '/Users/ivan/.docker/machine/certs/ca.pem'
    at Object.fs.openSync (fs.js:663:18)
    at Object.fs.readFileSync (fs.js:568:33)
    at Object.exports.copy (/usr/local/lib/node_modules/machine-share/util.js:5:17)
    at /usr/local/lib/node_modules/machine-share/export.js:44:14
    at Object.exports.recurseJson (/usr/local/lib/node_modules/machine-share/util.js:29:5)
```

I copied over the `ca.pem` from the specific machine dir into `certs/ca.pem` but then it asks for `certs/ca-key.pem` which I dont' know where to get that file.

Is `certs/ca-key.pem` the same as `certs/key.pem` ?

**Comment by ivanistheone** [comment]
Nevermind. For some reason my `certs/` dir hadn't copied over from my old laptop. I was able to get the certs dir from a backup, so all good now. Don't think either docker-machine or machine-share are at fault here.
