### ISSUE TITLE
import fails when docker-machine folder structure doesn't already exist

### ISSUE THREAD

**Issue by bodymindarts** [bhurlow/machine-share#6]
I have docker-machine installed in a docker container that is being run from a CI pipeline. When importing a machine for the first time the folder structure isn't set up correctly and import fails.

```
machine-import <machine-name>.zip
importing.
fs.js:634
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/root/.docker/machine/certs/<machine-name>/ca-key.pem'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.writeFileSync (fs.js:1327:33)
    at Object.exports.copy (/usr/lib/node_modules/machine-share/util.js:5:8)
    at Object.exports.copyDir (/usr/lib/node_modules/machine-share/util.js:14:21)
    at Object.<anonymous> (/usr/lib/node_modules/machine-share/import.js:35:6)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
```

running:

```
mkdir -p /root/.docker/machine/{machines,certs}
```

resolved the issue. Perhaps this can be taken care of on import.

Thank you very much for the tool however! Very useful despite the small quirks.

**Comment by tugberkugurlu** [comment]
I got the same error:

```
Foo-MBP:Downloads foo$ machine-import mymachine-temp-0.zip
importing.
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/foo/.docker/machine/machines/mymachine-temp-0/ca.pem'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at Object.exports.copy (/usr/local/lib/node_modules/machine-share/util.js:5:8)
    at Object.exports.copyDir (/usr/local/lib/node_modules/machine-share/util.js:14:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/machine-share/import.js:34:6)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

As @bodymindarts suggested, running `mkdir -p /Users/foo/.docker/machine/{machines,certs}` and running `machine-import` after solved the issue.

**Comment by JayBeavers** [comment]
Ditto, just hit this myself for both the machines and certs directories.  When failing on the certs directory missing, partially imported cruft was left in the machines directory that required cleanup.

**Comment by bhurlow** [comment]
hmmmm yea ok makes sense that it wouldn't exist if it was never created

**Comment by bhurlow** [comment]
If anyone would like to do a PR for this, you might get to it before I do as I've mostly completely stopped using docker machine :)

**Comment by colthreepv** [comment]
This issue should be fixed by using `mkdirp` in the latest release

**Comment by colthreepv** [comment]
Is this issue still valid? I vote for a close

**Comment by bhurlow** [comment]
@colthreepv closing, feel free to re-open if still an issue
