### ISSUE TITLE
osx - export fails with class FastBuffer extends Uint8Array {}

### ISSUE THREAD

**Issue by johndpope** [bhurlow/machine-share#7]
machine-export default
exporting.
buffer.js:8
class FastBuffer extends Uint8Array {}
^

RangeError: Invalid typed array length
    at Buffer.Uint8Array (native)
    at FastBuffer (buffer.js:8:1)
    at createUnsafeBuffer (buffer.js:33:12)
    at allocate (buffer.js:176:12)
    at Function.Buffer.allocUnsafe (buffer.js:136:10)
    at tryCreateBuffer (fs.js:474:21)
    at Object.fs.readFileSync (fs.js:519:14)
    at Object.exports.copy (/usr/local/lib/node_modules/machine-share/util.js:4:19)
    at Object.exports.copyDir (/usr/local/lib/node_modules/machine-share/util.js:14:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/machine-share/export.js:23:6)

**Comment by johndpope** [comment]
docker / toolbox now provides and export image. I'll close this.
