### ISSUE TITLE
windows not supported

### ISSUE THREAD

**Issue by colthreepv** [bhurlow/machine-share#9]
As far as I can see, trying to export anything fails because tries to write in `c:\tmp`, that's not the windows temp folder.

Stacktrace:

```
$ machine-export mymachine
exporting.
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\tmp\mymachine\ca.pem'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at Object.exports.copy (C:\Users\username\AppData\Roaming\npm\node_modules\machine-share\util.js:5:8)
    at Object.exports.copyDir (C:\Users\username\AppData\Roaming\npm\node_modules\machine-share\util.js:14:21)
    at Object.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\machine-share\export.js:23:6)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

**Comment by colthreepv** [comment]
fixed with #18 long time ago
